[package]
name = "swamp-symbol"
version = "0.2.19"
edition = "2024"
description = "unique symbol ids for Swamp"
repository = "https://github.com/swamp/swamp"
license = "MIT"

[dependencies]
source-map-node = "0.0.1"
seq-map = "0.0.14"
