[package]
name = "swamp-hir"
version = "0.1.0"
edition = "2024"

[dependencies]
swamp-ir-shared = { path = "../ir-shared" }
ansi-pretty-print = { path = "../../../../piot/ansi-pretty-print" }
[features]
debug-info = []
