[package]
name = "swamp-vm-debug-info"
version = "0.2.15"
edition = "2024"
license = "MIT"
description = "Debug info for the swamp vm"
repository = "https://github.com/swamp/swamp"

[dependencies]
swamp-vm-types = { path = "../vm-types", version = "0.2.15" }
seq-map = "0.0.13"
