[package]
name = "swamp"
version = "0.2.11"
edition = "2024"
license = "MIT"
repository = "https://github.com/swamp/swamp"
description = "script language for embedding"

[dependencies]
# Parser
swamp-parser = { path = "../parser", version = "0.2.11" } # TODO: This is only for an error. parser should not be a dependency

# Semantic and Analyzer
swamp-dep-loader = { path = "../dep-loader", version = "0.2.11" }
swamp-program-analyzer = { path = "../program-analyzer", version = "0.2.11" }
swamp-semantic = { path = "../semantic", version = "0.2.11" }
swamp-types = { path = "../types", version = "0.2.11" }
swamp-analyzer = { path = "../analyzer", version = "0.2.11" }
swamp-modules = { path = "../modules", version = "0.2.11" }

# Core
swamp-core = { path = "../core", version = "0.2.11" }

# Compile orchestrator
swamp-compile = { path = "../compile", version = "0.2.11" }

swamp-error-report = { path = "../err", version = "0.2.11" }

# Runtime and VM
swamp-code-gen = { path = "../code-gen", version = "0.2.11" }
swamp-vm = { path = "../vm", version = "0.2.11" }
swamp-vm-types = { path = "../vm-types", version = "0.2.11" }
# Not ready yet // swamp-vm-pretty-print = { path = "../vm-pretty-print", version = "0.2.0" }
swamp-runtime = { path = "../runtime", version = "0.2.11" }

swamp-vm-debug-info = { path = "../vm-debug-info", version = "0.2.11" }

# Source Map
source-map-cache = "0.0.3"
source-map-node = "0.0.1"

[dev-dependencies]
test-log = { version = "0.2.16", features = ["trace", "log", "color"] }
swamp-test-runner = { path = "../test-runner", version = "0.2.11" }

# Optional features for debugging and development
[features]
default = []
debug_vm = ["swamp-vm/debug_vm", "swamp-runtime/debug_vm"]
