[package]
name = "swamp-vm-isa"
version = "0.2.26"
edition = "2024"
license = "MIT"
description = "isa types for the Swamp VM"
repository = "https://github.com/swamp/swamp"

[dependencies]
hashmap-mem = "0.2.0"
