[package]
name = "swamp-types"
version = "0.2.23"
edition = "2024"
license = "MIT"
repository = "https://github.com/swamp/swamp"
description = "types used in Swamp"

[dependencies]
swamp-symbol = { path = "../symbol", version = "0.2.23" }
source-map-node = "0.0.1"
seq-map = "0.0.14"
seq-fmt = "0.0.1"
