[package]
name = "swamp-std"
version = "0.2.24"
edition = "2024"
license = "MIT"
repository = "https://github.com/swamp/swamp"
description = "Standard i/o functions for Swamp"

[dependencies]
swamp-vm = { path = "../vm", version = "0.2.24" }
swamp-vm-types = { path = "../vm-types", version = "0.2.24" }
swamp-vm-isa = { path = "../vm-isa", version = "0.2.24" }
[dev-dependencies]
