[package]
name = "swamp-build"
version = "0.2.4"
edition = "2024"
description = "swamp build tool"
license = "MIT"
repository = "https://github.com/swamp/swamp"

[dependencies]
swamp-runtime = { path = "../runtime", version = "0.2.4" }
pico-args = "0.5.0"

# Minimal tracing for production builds
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt", "ansi"], default-features = false }

[dev-dependencies]
